spring:

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: yoke
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

server:
  port: 8082